version: '3.8'

services:
  backend:
    build:
      context: ./Backend/api
      dockerfile: Dockerfile
    container_name: flask_api
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      MYSQL_HOST: db
      MYSQL_DATABASE: pianoclassification
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend/front-end
      dockerfile: Dockerfile
    container_name: react_frontend
    restart: always
    ports:
      - "3000:3000"

  db:
    image: mariadb:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pianoclassification
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: